#!/bin/zsh

alias free="free -h"
alias grep='grep --color=auto'
alias mkdir="mkdir -p"
alias n="nvim"
alias parun="paru --noconfirm --needed"
alias py="python3"
alias sc="sudo systemctl"
alias se="sudo -e"
alias v="vim"

alias vpnon="sudo wg-quick up zeus"
alias vpnoff="sudo wg-quick down zeus"
alias vpnfon="sudo wg-quick up zeus-full"
alias vpnfoff="sudo wg-quick down zeus-full"

alias dc="docker compose"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dcr="docker compose restart"
alias dcl="docker compose logs -f"

alias dark="gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
alias light="gsettings set org.gnome.desktop.interface color-scheme prefer-light"

alias ga="git add"
alias gaa="git add -A"
alias gc="git commit --signoff"
alias gcs="git commit --signoff -S"
alias gca="git commit --amend"
alias gcas="git commit --amend -S"
alias gcg="git commit -S && git commit --amend --signoff -S --no-edit"
alias gcn="git commit"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gcpc="git cherry-pick --continue"
alias gcps="git cherry-pick --signoff"
alias gd="git diff"
alias gdh="git diff HEAD"
alias gf="git fetch"
alias gg="git grep"
alias gl="git log"
alias glo="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an> <%cn>%Creset' --abbrev-commit"
alias gp="git push"
alias gpf="git push -f"
alias gr="git reset"
alias grb="git rebase"
alias grbs="git rebase --exec 'git commit --amend --no-edit -n -S'"
alias grh="git reset --hard"
alias gri="git rebase -i"
alias gris="git rebase --exec 'git commit --amend --no-edit -n -S' -i"
alias grm="git remote"
alias grv="git remote -v"
alias gs="git status"
alias gsh="git show"
