" https://github.com/tpope/vim-sensible
runtime! plugin/sensible.vim

" Tab -> 4 spaces
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab

" Auto indenting
"filetype plugin indent on
"set autoindent
"set paste

" Persistent undo
set undodir=~/.vim/undo-dir
set undofile

" Disable auto commenting
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro

" Visual indicator at 80 chars for git commit messages
autocmd FileType gitcommit setlocal colorcolumn=80

" Keep ~ clean
set viminfofile=~/.vim/.viminfo

" Prompt if directory doesn't exist
augroup vimrc-auto-mkdir
    autocmd!
    autocmd BufWritePre * call s:auto_mkdir(expand('<afile>:p:h'), v:cmdbang)
    function! s:auto_mkdir(dir, force)
        if !isdirectory(a:dir)
                    \   && (a:force
                    \       || input("'" . a:dir . "' does not exist. Create? [y/N]") =~? '^y\%[es]$')
            call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
        endif
    endfunction
augroup END

